/* Generated By:JavaCC: Do not edit this line. DoclipseParserConstants.java */
package com.beust.doclipsen.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DoclipseParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAG = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"*\"",
    "<TAG>",
    "<IDENTIFIER>",
    "<STRING>",
    "\".\"",
    "\"=\"",
  };

}
